version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: go_bitly_pg
    env_file:
      - ./config/docker.env
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
